### ISSUE TITLE
ipAddress missing: use NAMECHEAP_CLIENT_IP_ADDRESS environment variable

### ISSUE THREAD

**Issue by pavelsr** [stevenzeiler/namecheap-cli#1]
Hi,

Run your installed cli-tool and got:

```
pavel@pavel-VirtualBox:~/projects/namecheap$ namecheap --help
/usr/lib/node_modules/namecheap-cli/lib/NamecheapClient.js:16
    throw new Error('ipAddress missing: use NAMECHEAP_CLIENT_IP_ADDRESS environment variable')
    ^

Error: ipAddress missing: use NAMECHEAP_CLIENT_IP_ADDRESS environment variable
    at module.exports.config (/usr/lib/node_modules/namecheap-cli/lib/NamecheapClient.js:16:11)
    at Object.<anonymous> (/usr/lib/node_modules/namecheap-cli/bin/namecheap-cli.js:6:49)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
```

What is the NAMECHEAP_CLIENT_IP_ADDRESS environment variable?

**Comment by luiscachog** [comment]
Same error here.

**Comment by ryanerwin** [comment]
To use the namecheap CLI tool, you'll need to request API access in your namecheap account.

https://www.namecheap.com/support/api/intro/

The Namecheap API appears to require your clients to use a static IP, so it's really more designed for resellers than pure CLI access.

NamecheapClient.js appears to use Node's config package

https://www.npmjs.com/package/config

```
   config.ipAddress = config.apiAddress || process.env['NAMECHEAP_CLIENT_IP_ADDRESS']¬
   config.apiKey = config.apiKey || process.env['NAMECHEAP_API_KEY']¬
   config.apiUser = config.apiUser || process.env['NAMECHEAP_API_USER']
```
